name: Test Kani
on:
  push:
    paths:
      - 'Formula/kani.rb'
  workflow_dispatch:

jobs:
  setup-kani:
    runs-on: macos-latest
    steps:
      - name: Install Kani
        run: brew install ronakfof/litani/kani
      - name: Test kani
        run: brew test kani
  test-kani-standalone:
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: |
          brew install ronakfof/litani/viewer@2.6 cbmc rustup-init
          pip3 install autopep8 toml colorama
      - name: setup dependencies
        run: |
          rustup-init -y --default-toolchain nightly
          source $HOME/.cargo/env
      - name: Clone Kani
        run: git clone https://github.com/model-checking/kani.git
      - name: Build Kani
        run: |
          cd kani
          git submodule update --init --depth 1
          cargo build
          ./scripts/kani-regression.sh
          export PATH=$(pwd)/scripts:$PATH
        