on:
  push:
    paths:
      - 'Formula/kani.rb'
  workflow_dispatch:

jobs:
  setup-kani:
    runs-on: macos-latest
    steps:
      - name: Tap repo
        run: brew tap ronakfof/litani/kani
      - name: Install Kani
        run: brew install kani
      - name: Test kani
        run: brew test kani
        